// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4zrJAv6autooCrkFl6jwrwPLlP508SE',
    appId: '1:144207693896:web:cb2d5254b3db6cad45707d',
    messagingSenderId: '144207693896',
    projectId: 'e-commerce-app-flutter-6810a',
    authDomain: 'e-commerce-app-flutter-6810a.firebaseapp.com',
    storageBucket: 'e-commerce-app-flutter-6810a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSxHlPYGvlxBWD1uka9Aonz0SFKL3ScLg',
    appId: '1:144207693896:android:f17f3a21b1102b3145707d',
    messagingSenderId: '144207693896',
    projectId: 'e-commerce-app-flutter-6810a',
    storageBucket: 'e-commerce-app-flutter-6810a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2_fRC793_UQFPskp0aDI2TIH7GWyZbhg',
    appId: '1:144207693896:ios:e8e8e41d55c2502c45707d',
    messagingSenderId: '144207693896',
    projectId: 'e-commerce-app-flutter-6810a',
    storageBucket: 'e-commerce-app-flutter-6810a.appspot.com',
    iosClientId: '144207693896-j42dugrc65ghobc68fcjb5na0cgv1f3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2_fRC793_UQFPskp0aDI2TIH7GWyZbhg',
    appId: '1:144207693896:ios:e8e8e41d55c2502c45707d',
    messagingSenderId: '144207693896',
    projectId: 'e-commerce-app-flutter-6810a',
    storageBucket: 'e-commerce-app-flutter-6810a.appspot.com',
    iosClientId: '144207693896-j42dugrc65ghobc68fcjb5na0cgv1f3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
